name: Deploy to GKE Cluster
run-name: Deploy Image Tag ${{ inputs.image_tag }} by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image Tag'
        required: true

env:
  PROJECT_ID: ${{secrets.GCLOUD_PROJECTID}}
  GKE_CLUSTER: cluster-1
  GKE_ZONE: us-central1-c
  IMAGE: contact-service
  TAG: ${{ github.sha }}
  USE_GKE_GCLOUD_AUTH_PLUGIN: true

jobs:
  setup-deploy:
    environment: test_env
    name: Setup and Deploy
    runs-on: ubuntu-latest
    env:
      working-directory: ./

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          service_account_key: ${{secrets.KUBERNETES_DEPLOYER_SECRET_KEY}}
          project_id: ${{ env.PROJECT_ID }}

      - name: Install Gcloud auth plugin
        run: gcloud components install gke-gcloud-auth-plugin

      - name: Get GKE Credentials
        run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE" --project "$PROJECT_ID"

      - name: Set up Helm
        run: |
          HELM_VERSION="v3.15.3"
          curl -LO https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz
          tar -zxvf helm-${HELM_VERSION}-linux-amd64.tar.gz
          sudo mv linux-amd64/helm /usr/local/bin/helm

      - name: Verify Helm installation
        run: helm version

      - name: Install contact-service
        run: |
          helm upgrade --install contact-service helm/contact-service --namespace default