name: Build and Release to Artifactory
run-name: Release Image Tag ${{ github.sha }} by @${{ github.actor }}
on:
  workflow_dispatch:

env:
  PROJECT_ID: ${{secrets.GCLOUD_PROJECTID}}
  GKE_CLUSTER: learning-app-cluster
  GKE_ZONE: us-central1-c
  DEPLOYMENT_NAME: contact-service
  IMAGE: contact-service
  TAG: ${{ github.sha }}
  USE_GKE_GCLOUD_AUTH_PLUGIN: true

jobs:
  setup-build-release:
    name: Setup Build and Release
    runs-on: ubuntu-latest
    env:
      working-directory: ./

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build Projects
        run: |-
          bash ./gradlew clean build

#      - name: Setup Gcloud CLI
#        uses: google-github-actions/setup-gcloud@v2
#        env:
#          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
#        with:
#          credentials_json: ${{secrets.KUBERNETES_DEPLOYER_SECRET_KEY}}
#          project_id: ${{secrets.GCLOUD_PROJECTID}}

#      - name: Install Gcloud auth plugin
#        run: gcloud components install gke-gcloud-auth-plugin

      - name: Configure Docker
        run: |-
          gcloud --quiet auth configure-docker

#      - name: Get GKE Credentials
#        run: |-
#          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE" --project "$PROJECT_ID"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |-
          docker build -t "${{secrets.DOCKER_USERNAME}}/$IMAGE:$TAG" .

      - name: Publish Docker Image to Docker Hub
        run: |-
          docker push "${{secrets.DOCKER_USERNAME}}/$IMAGE:$TAG"